---
# tasks file for linux_install
- name: Include OS-specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Templating sudoers.d file
  copy:
    src: jose
    dest: /etc/sudoers.d/jose
    mode: '0440'

- name: Templating motd.d
  copy:
    src: 01-welcome
    dest: /etc/update-motd.d/01-welcome
    mode: '0755'

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Add the user 'jose', appending the group 'docker' to the user's groups
  user:
    name: jose
    groups: docker
    append: yes

- name: Configuring zabbix_agent2.conf
  lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  with_items:
    - regex: '^Hostname='
      line: Hostname={{ ansible_hostname }}
    - regex: '^Server='
      line: Server={{ zbx_srv_ip }}
    - regex: '^ServerActive='
      line: ServerActive={{ zbx_srv_act_ip }}
    - regex: '^\# HostMetadata='
      line: HostMetadata=linux

- name: Restart Zabbix agent
  service:
    name: zabbix-agent2
    state: restarted

- name: Start and enable qemu-guest-agent
  service:
    name: qemu-guest-agent
    state: restarted
    enabled: true